version: '2'

services:
  db-book-app:
    image: 'postgres:13.1-alpine'
    container_name: db-book-app
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres